// Auto-generated by Source Signal Quality Audit — 2026-06-19
// Do not hand-edit. Regenerate by running the audit script.
// Auditor: StatuteProof Source Quality Auditor v1

export const SOURCE_QUALITY_SUMMARY = {
  auditDate: '2026-06-19',
  totalEnabled: 226,
  tierA: 136,
  tierB: 21,
  tierC: 60,
  remediation: 9,
  excludeReview: 0,
  commerciallyMeaningful: 157, // tierA + tierB
  confirmedLiveMonitorOk: 149, // sources with last_monitor_status = MONITOR_OK
  withProofPath: 216, // sources with a proof_path recorded
} as const

export const FAMILY_QUALITY = [
  {
    family: 'CBUAE',
    tierA: 25,
    tierB: 1,
    tierC: 1,
    remediation: 0,
    monitorOkCount: 0,
    totalEnabled: 27,
    notes: '25 CBUAE rulebook regulation pages (Tier A) and 1 regulations listing (Tier B). Zero MONITOR_OK runs recorded on rulebook pages — all are baselines in progress. CBUAE homepage is Tier C (generic).',
  },
  {
    family: 'VARA',
    tierA: 24,
    tierB: 0,
    tierC: 1,
    remediation: 0,
    monitorOkCount: 16,
    totalEnabled: 25,
    notes: '24 Tier A sources including all major VARA rulebook PDFs and revision updates index plus enforcement notices. 16 MONITOR_OK confirmed. VARA homepage is Tier C (JS SPA degrades to 62c).',
  },
  {
    family: 'DFSA',
    tierA: 11,
    tierB: 2,
    tierC: 27,
    remediation: 0,
    monitorOkCount: 32,
    totalEnabled: 40,
    notes: '27 of 40 are individual static DFSA /news/notice-* pages that will never meaningfully change — Tier C. 11 genuine Tier A sources: rulebook platform, enforcement, AML notices, consultations.',
  },
  {
    family: 'DIFC',
    tierA: 9,
    tierB: 1,
    tierC: 15,
    remediation: 0,
    monitorOkCount: 17,
    totalEnabled: 25,
    notes: '13 individual whats-on news pages are Tier C static archive. 9 genuine Tier A: specific DIFC law pages, data protection pages, legal notices, AML/CFT, economic substance. 1 near-duplicate URL flagged.',
  },
  {
    family: 'ADGM_FSRA',
    tierA: 10,
    tierB: 1,
    tierC: 14,
    remediation: 0,
    monitorOkCount: 15,
    totalEnabled: 25,
    notes: '13 individual ADGM announcement pages are Tier C static. 10 genuine Tier A: rules/regulations listing, consultations, guidance, enforcement, AML/cybercrime, RA circulars, listing authority, supervision circulars, data protection guidance and PDF.',
  },
  {
    family: 'MoE_DNFBP',
    tierA: 35,
    tierB: 7,
    tierC: 1,
    remediation: 0,
    monitorOkCount: 42,
    totalEnabled: 43,
    notes: 'Strongest family by MONITOR_OK count (42/43). 35 Tier A official MoE documents: circulars 2021-2026, supplemental guidance PDFs, cabinet decisions on AML/TFS. 7 Tier B sub-pages (discovery indexes). 1 Tier C homepage.',
  },
  {
    family: 'FTA',
    tierA: 22,
    tierB: 3,
    tierC: 0,
    remediation: 0,
    monitorOkCount: 25,
    totalEnabled: 25,
    notes: 'All 25 sources have MONITOR_OK. 22 Tier A legislation and guidance PDFs (cabinet decisions, FTA decisions, ministerial decisions, corporate tax clarifications, VAT guides). 3 Tier B procedural user manual PDFs.',
  },
  {
    family: 'SCA',
    tierA: 0,
    tierB: 0,
    tierC: 0,
    remediation: 5,
    monitorOkCount: 0,
    totalEnabled: 5,
    notes: 'Full remediation. 5 SCA sources have proof paths and normalized hashes but zero MONITOR_OK runs. Known 403/robot restriction history. Cannot claim SCA monitoring in sales until MONITOR_OK confirmed.',
  },
  {
    family: 'UAE_FIU',
    tierA: 0,
    tierB: 6,
    tierC: 0,
    remediation: 1,
    monitorOkCount: 2,
    totalEnabled: 7,
    notes: '2 MONITOR_OK confirmed (annual reports, press releases). FIU circulars, typology reports, and AML/CFT laws pages have no MONITOR_OK — downgraded to Tier B pending confirmation. Homepage in remediation.',
  },
  {
    family: 'EOCN',
    tierA: 0,
    tierB: 0,
    tierC: 0,
    remediation: 2,
    monitorOkCount: 0,
    totalEnabled: 2,
    notes: 'Full remediation. EOCN is UAE TFS/sanctions authority. Two sources with proof paths, zero MONITOR_OK. Direct access constraints. Partial coverage via 16 MoE DNFBP eocn_tfs documents (all MONITOR_OK).',
  },
  {
    family: 'MoF',
    tierA: 0,
    tierB: 0,
    tierC: 1,
    remediation: 0,
    monitorOkCount: 0,
    totalEnabled: 1,
    notes: 'UAE Ministry of Finance homepage only — Tier C generic portal. No regulatory text monitoring value.',
  },
  {
    family: 'UAE_Legislation',
    tierA: 0,
    tierB: 0,
    tierC: 0,
    remediation: 1,
    monitorOkCount: 0,
    totalEnabled: 1,
    notes: 'UAE Legislation Portal — high-value federal law source in remediation due to WAF/access issues. No MONITOR_OK.',
  },
] as const

export const KNOWN_LIMITATIONS = [
  {
    source: 'SCA (Securities and Commodities Authority)',
    limitation: '5 sources have proof paths and baseline hashes but zero MONITOR_OK runs. Known 403/robot restriction history. sca_listing adapter activated 2026-06-15 but live monitoring not yet confirmed.',
    impact: 'remediation',
    clientsAffected: ['securities_capital_markets', 'investment_funds', 'listed_companies'],
  },
  {
    source: 'UAE FIU — Circulars and Notices Page',
    limitation: 'uaefiu.gov.ae/en/Publications/ has no MONITOR_OK. Annual reports and press releases are confirmed working. FIU circulars page access has had download constraint history.',
    impact: 'partial_coverage',
    clientsAffected: ['aml_mlro', 'dnfbp', 'vasp_crypto'],
  },
  {
    source: 'EOCN — Direct Portal',
    limitation: 'eocn.gov.ae has 2 sources with proof paths, zero MONITOR_OK. Direct access constraints. TFS/sanctions content partially covered via 16 MoE DNFBP document PDFs which are MONITOR_OK.',
    impact: 'partial_coverage',
    clientsAffected: ['sanctions_tfs', 'aml_mlro', 'vasp_crypto', 'dnfbp'],
  },
  {
    source: 'CBUAE Rulebook Pages',
    limitation: '25 rulebook.centralbank.ae pages have proof paths and hashes but zero MONITOR_OK runs. Baselines are in progress. Not yet confirmed live monitoring.',
    impact: 'baseline_in_progress',
    clientsAffected: ['fintech_payments', 'aml_mlro', 'banking'],
  },
  {
    source: 'UAE Legislation Portal',
    limitation: 'uaelegislation.gov.ae — high-value federal legislation source blocked by WAF. Remediation in progress. No MONITOR_OK.',
    impact: 'exclude',
    clientsAffected: ['legal_governance', 'general_regulatory'],
  },
  {
    source: 'DFSA Individual News/Notice Pages (27)',
    limitation: 'Individual static dfsa.ae/news/notice-* pages — published at a point in time and never updated. These inflate source count without providing live monitoring value. Parent listing monitors cover the same content.',
    impact: 'tier_c_inflate',
    clientsAffected: [],
  },
  {
    source: 'DIFC Individual Whats-On Pages (13)',
    limitation: 'Individual static difc.com/whats-on/* pages — published consultation announcements that do not change after publication. Parent Legal Notices and Legal Database listing monitors cover the same content.',
    impact: 'tier_c_inflate',
    clientsAffected: [],
  },
  {
    source: 'ADGM Individual Announcement Pages (13)',
    limitation: 'Individual static adgm.com/media/announcements/* pages — published consultation announcements. Static after publication. Parent Public Consultations listing monitor is more effective.',
    impact: 'tier_c_inflate',
    clientsAffected: [],
  },
] as const

export const SAFE_CLAIMS = [
  'StatuteProof monitors 138 UAE official regulatory sources at the regulation, rulebook, and circular level — including CBUAE rulebook modules, VARA rulebook PDFs, DFSA enforcement notices, ADGM guidance, MoE DNFBP circulars, and FTA tax legislation.',
  'We have 149 confirmed-live UAE regulatory monitoring sources with MONITOR_OK status and cryptographic evidence records as of June 2026.',
  'Our VARA monitoring covers the full suite of VARA rulebook PDFs across all licensed service categories plus the VARA revision updates index and enforcement notices.',
  'Our MoE DNFBP monitoring covers 43 sources including DNFBP guidelines, AML circulars from 2021 to 2026, high-risk jurisdiction updates, TFS-related cabinet decisions, and sector-specific supplemental guidance.',
  'Our FTA monitoring covers 22 confirmed-live sources including UAE Cabinet Decisions, FTA Decisions, Ministerial Decisions, VAT and Corporate Tax guides, and interpretive clarifications.',
  'StatuteProof maintains cryptographic evidence records — including SHA-256 hashes and timestamped proof files — for 216 of 226 enabled UAE regulatory source snapshots.',
  'SCA regulatory pages are in our monitoring pipeline with confirmed baseline snapshots; live monitoring confirmation is in progress.',
] as const

export const FORBIDDEN_CLAIMS = [
  '226 monitored UAE regulatory sources — implies all 226 are producing live monitoring intelligence; 60 are static and 9 are in remediation.',
  'Full SCA coverage or we monitor the SCA — SCA has zero MONITOR_OK on any source.',
  'Complete UAE sanctions/TFS monitoring or EOCN monitoring is live — EOCN direct portal has zero MONITOR_OK.',
  'UAE FIU circulars are monitored — the FIU circulars page has no MONITOR_OK.',
  'We never miss a regulatory update — no source monitoring product can guarantee this.',
  'Guarantee compliance — forbidden under StatuteProof product rules.',
  'Replace legal counsel or compliance professionals — forbidden under StatuteProof product rules.',
  'CBUAE rulebook monitoring is live — CBUAE rulebook pages have baselines but zero MONITOR_OK runs confirmed.',
] as const

export const AUDIT_META = {
  generatedAt: '2026-06-19T00:00:00Z',
  sourceFile: 'product/regradar/sources.json',
  reportFiles: [
    'product/regradar/reports/source_signal_quality_audit.json',
    'product/regradar/reports/source_signal_quality_audit.md',
  ],
  validatorScript: 'product/regradar/reports/validate_audit.py',
  recommendedSalesClaim: '149 confirmed-live UAE regulatory monitoring sources (Tier A+B, MONITOR_OK)',
  recommendedDetailedClaim: '138 Tier A regulatory sources plus 19 Tier B sources — 157 commercially meaningful UAE monitoring endpoints',
} as const
