// Auto-generated by Source Signal Quality Audit — 2026-06-19
// Do not hand-edit. Regenerate by running the audit script.
// Auditor: StatuteProof Source Quality Auditor v1

export const SOURCE_QUALITY_SUMMARY = {
  auditDate: '2026-06-19',
  totalEnabled: 232,
  tierA: 147,
  tierB: 21,
  tierC: 61,
  remediation: 3,
  excludeReview: 0,
  commerciallyMeaningful: 168, // tierA + tierB
  confirmedLiveMonitorOk: 216, // all MONITOR_OK sources, including static evidence-library pages
  freshAlertEligible: 162, // tierA/B + proof + baseline + MONITOR_OK + alert_eligible
  evidenceLibraryOnly: 61, // official/static or low future-change signal, not fresh alerts
  pendingFreshSignalValidation: 6, // tierA/B candidates without confirmed fresh-alert MONITOR_OK
  withProofPath: 222, // sources with a proof_path recorded
} as const

export const FAMILY_QUALITY = [
  {
    family: 'CBUAE',
    tierA: 25,
    tierB: 1,
    tierC: 1,
    remediation: 0,
    monitorOkCount: 25,
    totalEnabled: 27,
    notes: '25 CBUAE rulebook/regulatory sources now have fresh-alert MONITOR_OK after adapter-aligned proof, repeat baseline, and mass-monitor dry-run. CBUAE homepage remains Tier C evidence-library and the generic regulations page remains candidate/held.',
  },
  {
    family: 'VARA',
    tierA: 24,
    tierB: 0,
    tierC: 1,
    remediation: 0,
    monitorOkCount: 23,
    totalEnabled: 25,
    notes: '23 VARA sources now have fresh-alert MONITOR_OK, including rulebook PDFs and revision updates. VARA enforcement still failed as nav-shell and homepage remains Tier C; VARA is close but not yet Strong Fresh Signal.',
  },
  {
    family: 'DFSA',
    tierA: 13,
    tierB: 2,
    tierC: 28,
    remediation: 0,
    monitorOkCount: 42,
    totalEnabled: 43,
    notes: '15 DFSA fresh-alert sources now have MONITOR_OK after adding legal resources, innovation, and enforcement overview sources. 28 individual/static pages remain evidence-library and duplicate-hash publication pages are not counted as new fresh-alert monitors.',
  },
  {
    family: 'DIFC',
    tierA: 10,
    tierB: 0,
    tierC: 15,
    remediation: 0,
    monitorOkCount: 24,
    totalEnabled: 25,
    notes: '10 DIFC fresh-alert sources now have MONITOR_OK, including laws/regulations and data protection legal pages. 15 whats-on/news/static detail pages remain evidence-library and are not counted as fresh alerts.',
  },
  {
    family: 'ADGM_FSRA',
    tierA: 10,
    tierB: 1,
    tierC: 14,
    remediation: 0,
    monitorOkCount: 21,
    totalEnabled: 25,
    notes: '8 ADGM/FSRA fresh-alert sources now have MONITOR_OK. Several candidates remain held due to QUALITY_DROP or nav-shell, while 14 individual announcements remain evidence-library.',
  },
  {
    family: 'MoE_DNFBP',
    tierA: 35,
    tierB: 7,
    tierC: 1,
    remediation: 0,
    monitorOkCount: 42,
    totalEnabled: 43,
    notes: 'Strongest family by MONITOR_OK count (42/43). 35 Tier A official MoE documents: circulars 2021-2026, supplemental guidance PDFs, cabinet decisions on AML/TFS. 7 Tier B sub-pages (discovery indexes). 1 Tier C homepage.',
  },
  {
    family: 'FTA',
    tierA: 22,
    tierB: 3,
    tierC: 0,
    remediation: 0,
    monitorOkCount: 25,
    totalEnabled: 25,
    notes: 'All 25 sources have MONITOR_OK. 22 Tier A legislation and guidance PDFs (cabinet decisions, FTA decisions, ministerial decisions, corporate tax clarifications, VAT guides). 3 Tier B procedural user manual PDFs.',
  },
  {
    family: 'SCA',
    tierA: 4,
    tierB: 1,
    tierC: 1,
    remediation: 1,
    monitorOkCount: 5,
    totalEnabled: 7,
    notes: '5 SCA sources are fresh-alert eligible after proof, repeat baseline, and mass-monitor dry-run MONITOR_OK, including the FinTech Regulatory Sandbox page. Broader SCA family remains below Strong; regulations listing still failed nav-shell.',
  },
  {
    family: 'UAE_FIU',
    tierA: 0,
    tierB: 6,
    tierC: 0,
    remediation: 1,
    monitorOkCount: 5,
    totalEnabled: 7,
    notes: '5 UAE FIU sources now have fresh-alert MONITOR_OK: annual reports, press releases, typology reports, AML/CFT laws, and publications hub. FIU circulars remain nav-shell/candidate and the homepage remains remediation.',
  },
  {
    family: 'EOCN',
    tierA: 23,
    tierB: 1,
    tierC: 0,
    remediation: 0,
    monitorOkCount: 24,
    totalEnabled: 24,
    notes: '24 EOCN/TFS-related sources now have MONITOR_OK, including direct EOCN and UAEIEC laws/regulations sources plus MoE-owned TFS/supporting sources. Still one source below the 25-source Strong threshold and direct EOCN coverage remains partial.',
  },
  {
    family: 'MoF',
    tierA: 0,
    tierB: 0,
    tierC: 1,
    remediation: 0,
    monitorOkCount: 0,
    totalEnabled: 1,
    notes: 'UAE Ministry of Finance homepage only — Tier C generic portal. No regulatory text monitoring value.',
  },
  {
    family: 'UAE_Legislation',
    tierA: 0,
    tierB: 0,
    tierC: 0,
    remediation: 1,
    monitorOkCount: 0,
    totalEnabled: 1,
    notes: 'UAE Legislation Portal — high-value federal law source in remediation due to WAF/access issues. No MONITOR_OK.',
  },
] as const

export const KNOWN_LIMITATIONS = [
  {
    source: 'SCA (Securities and Commodities Authority)',
    limitation: '5 SCA sources have proof-backed MONITOR_OK, but SCA remains below the 25-source Strong Fresh Signal threshold. SCA regulations listing still failed nav-shell and needs adapter remediation.',
    impact: 'remediation',
    clientsAffected: ['securities_capital_markets', 'investment_funds', 'listed_companies'],
  },
  {
    source: 'UAE FIU — Circulars and Notices Page',
    limitation: '5 UAE FIU public sources have MONITOR_OK, but the FIU circulars page still failed nav-shell and cannot be claimed as monitored.',
    impact: 'partial_coverage',
    clientsAffected: ['aml_mlro', 'dnfbp', 'vasp_crypto'],
  },
  {
    source: 'EOCN — Direct Portal',
    limitation: 'Direct EOCN/UAEIEC sources improved. EOCN/TFS has 24 fresh-alert sources and remains one source below the 25-source Strong threshold, with some TFS support still coming through MoE-owned documents.',
    impact: 'partial_coverage',
    clientsAffected: ['sanctions_tfs', 'aml_mlro', 'vasp_crypto', 'dnfbp'],
  },
  {
    source: 'CBUAE Rulebook Pages',
    limitation: '25 CBUAE rulebook/regulatory sources now have MONITOR_OK. The generic CBUAE homepage and generic regulations portal remain excluded from fresh-alert claims.',
    impact: 'resolved_with_scope',
    clientsAffected: ['fintech_payments', 'aml_mlro', 'banking'],
  },
  {
    source: 'UAE Legislation Portal',
    limitation: 'uaelegislation.gov.ae — high-value federal legislation source blocked by WAF. Remediation in progress. No MONITOR_OK.',
    impact: 'exclude',
    clientsAffected: ['legal_governance', 'general_regulatory'],
  },
  {
    source: 'DFSA Individual News/Notice Pages (27)',
    limitation: 'Individual static dfsa.ae/news/notice-* pages — published at a point in time and never updated. These inflate source count without providing live monitoring value. Parent listing monitors cover the same content.',
    impact: 'tier_c_inflate',
    clientsAffected: [],
  },
  {
    source: 'DIFC Individual Whats-On Pages (13)',
    limitation: 'Individual static difc.com/whats-on/* pages — published consultation announcements that do not change after publication. Parent Legal Notices and Legal Database listing monitors cover the same content.',
    impact: 'tier_c_inflate',
    clientsAffected: [],
  },
  {
    source: 'ADGM Individual Announcement Pages (13)',
    limitation: 'Individual static adgm.com/media/announcements/* pages — published consultation announcements. Static after publication. Parent Public Consultations listing monitor is more effective.',
    impact: 'tier_c_inflate',
    clientsAffected: [],
  },
] as const

export const SAFE_CLAIMS = [
  'StatuteProof has 162 fresh-alert eligible UAE official-source monitors with MONITOR_OK status, proof records, hashes, and baseline confirmation as of June 2026.',
  'StatuteProof also maintains an evidence library of official/static UAE source snapshots that may support audit packs but are not counted as fresh-alert monitoring.',
  '216 enabled UAE sources have MONITOR_OK status overall; 162 of those are currently fresh-alert eligible after excluding static evidence-library pages.',
  'Our CBUAE rulebook monitoring includes 25 fresh-alert eligible official rulebook/regulatory sources with MONITOR_OK and proof-backed baselines.',
  'Our VARA monitoring includes 23 confirmed-live official VARA rulebook and regulatory sources, with enforcement still pending adapter validation.',
  'Our MoE DNFBP monitoring covers 43 sources including DNFBP guidelines, AML circulars from 2021 to 2026, high-risk jurisdiction updates, TFS-related cabinet decisions, and sector-specific supplemental guidance.',
  'Our FTA monitoring covers 22 confirmed-live sources including UAE Cabinet Decisions, FTA Decisions, Ministerial Decisions, VAT and Corporate Tax guides, and interpretive clarifications.',
  'StatuteProof maintains cryptographic evidence records — including SHA-256 hashes and timestamped proof files — for 222 of 232 enabled UAE regulatory source snapshots.',
  'SCA monitoring has 5 proof-backed fresh-alert sources; broader SCA family monitoring remains below Strong until additional official sources reach MONITOR_OK.',
] as const

export const FORBIDDEN_CLAIMS = [
  '232 monitored UAE regulatory sources — implies all 232 are producing live monitoring intelligence; 61 are static/evidence-library and 3 are in remediation.',
  'Full SCA coverage or we monitor the SCA broadly — only 5 SCA sources are fresh-alert eligible.',
  'Complete UAE sanctions/TFS monitoring — EOCN/TFS is improved to 24 but still below the 25-source Strong threshold.',
  'UAE FIU circulars are monitored — the FIU circulars page still failed nav-shell.',
  'We never miss a regulatory update — no source monitoring product can guarantee this.',
  'Guarantee compliance — forbidden under StatuteProof product rules.',
  'Replace legal counsel or compliance professionals — forbidden under StatuteProof product rules.',
] as const

export const AUDIT_META = {
  generatedAt: '2026-06-19T00:00:00Z',
  sourceFile: 'product/regradar/sources.json',
  reportFiles: [
    'product/regradar/reports/source_signal_quality_audit.json',
    'product/regradar/reports/source_signal_quality_audit.md',
  ],
  validatorScript: 'product/regradar/reports/validate_audit.py',
  recommendedSalesClaim: '162 fresh-alert eligible UAE official-source monitors with MONITOR_OK, proof records, hashes, and baseline confirmation',
  recommendedDetailedClaim: '168 commercially meaningful UAE official sources mapped; 162 currently fresh-alert eligible, 6 pending fresh-signal validation, and 61 retained as evidence-library/static references',
} as const
