import { ArrowLeft, ShieldCheck } from 'lucide-react'
import { CONTACT_EMAIL } from '../data/constants'

// ─────────────────────────────────────────────────────────────────────────────
// Content blocks — intentionally detailed for a B2B compliance intelligence
// product. Each section is a { heading, paragraphs[] } object.
// ─────────────────────────────────────────────────────────────────────────────

const TERMS_SECTIONS = [
  {
    heading: '1. Service description and scope',
    paragraphs: [
      'StatuteProof provides official-source monitoring intelligence, SHA-256–verified source evidence records, and review-support summaries for selected UAE public regulatory sources. StatuteProof is not a legal information service, a legal database, or a regulatory authority.',
      'The service monitors selected publicly accessible URLs published by UAE regulatory bodies such as the Virtual Assets Regulatory Authority (VARA), Central Bank of the UAE (CBUAE), Dubai Financial Services Authority (DFSA), Abu Dhabi Global Market Financial Services Regulatory Authority (ADGM/FSRA), UAE Capital Market Authority (UAE CMA, formerly SCA), Dubai International Financial Centre (DIFC), and the UAE Federal Tax Authority (FTA). Which specific sources are actively monitored — together with source coverage, extraction quality, and access limitations, including regulator sites that are not currently accessible for monitoring (for example the UAE Financial Intelligence Unit portal) — are disclosed in the Source Readiness Review prior to pilot activation.',
      'StatuteProof does not provide legal advice, regulatory advice, compliance determination, or a legal opinion. It does not replace qualified legal counsel, compliance professionals, Money Laundering Reporting Officers (MLROs), or other professional advisers. Nothing in this service or its outputs constitutes a legal or compliance opinion.',
    ],
  },
  {
    heading: '2. Eligibility and account access',
    paragraphs: [
      'Access to StatuteProof is limited to legal entities, compliance professionals, and individuals operating in a professional capacity with a legitimate compliance monitoring use case. By registering, you confirm that you meet this requirement.',
      'Each workspace is activated manually following a Source Readiness Review. Activation is at StatuteProof\'s sole discretion. We reserve the right to decline or suspend access where use does not align with the intended purpose of the service.',
      'You are responsible for maintaining the confidentiality of your login credentials and for all activity that occurs under your account. Notify us immediately at ' + CONTACT_EMAIL + ' if you suspect unauthorised access.',
    ],
  },
  {
    heading: '3. Use restrictions',
    paragraphs: [
      'You may not use StatuteProof to provide legal or regulatory advice to third parties, republish monitoring briefs or evidence records as official regulatory guidance, or represent StatuteProof outputs as certified, complete, or authoritative records of regulatory activity.',
      'You may not attempt to access, scrape, or reverse-engineer the monitoring infrastructure, submit custom source URLs that contain confidential, non-public, or access-controlled regulatory material, or use the service in a manner that would constitute practice of law in any jurisdiction.',
      'Automated access to the web interface without prior written agreement is prohibited. API access, if available, is subject to separate usage terms.',
    ],
  },
  {
    heading: '4. Evidence records and monitoring outputs',
    paragraphs: [
      'StatuteProof produces cryptographic evidence records for each monitored source run. Each record includes the source URL, a SHA-256 hash of the extracted content, a UTC timestamp, and a change-status label (FIRST_SEEN, UNCHANGED, CHANGED, FAILED, or QUALITY_DROP). These records are intended to support internal compliance documentation workflows — they are not court-ready forensic evidence and have not been independently audited.',
      'Monitoring briefs and alert drafts generated by StatuteProof are prepared from extracted source text using rule-based and AI-assisted analysis. They represent a starting point for human compliance review. They may contain errors, omissions, or content that has become stale due to publication delays, website structure changes, PDF formatting issues, or access restrictions at the source. Human review and independent verification of primary source material is required before any brief or alert is acted upon.',
      'Evidence retention periods are determined by your plan. StatuteProof makes reasonable efforts to maintain data availability within those periods but does not guarantee uninterrupted access.',
    ],
  },
  {
    heading: '5. Payment and billing',
    paragraphs: [
      'Founding Pilot and UAE Monitor plans are billed monthly. Payment is processed via Stripe. By providing payment details you authorise recurring charges at the applicable plan rate until you cancel.',
      'No payment is taken and no card is stored during the Source Readiness Review or prior to manual pilot activation. Billing begins on the date your workspace is formally activated.',
      'Refund requests within 7 days of the first charge may be submitted to ' + CONTACT_EMAIL + ' and will be reviewed on a case-by-case basis. No refunds are available for partial months after the 7-day window.',
      'Plan prices are stated in USD. We reserve the right to adjust prices with 30 days written notice to your registered email.',
    ],
  },
  {
    heading: '6. Intellectual property',
    paragraphs: [
      'StatuteProof and its underlying technology, software, monitoring methodology, and user interface are owned by StatuteProof and protected by applicable intellectual property laws.',
      'Extracted text from public regulatory sources is the property of the issuing regulatory authority. StatuteProof does not claim ownership of source text. Your use of extracted content is subject to any terms published by the originating authority.',
      'You retain ownership of any custom compliance notes, annotations, or documentation you create within the service.',
    ],
  },
  {
    heading: '7. Limitation of liability',
    paragraphs: [
      'To the maximum extent permitted by applicable law, StatuteProof\'s total liability for any claim arising from these Terms or the use of the service shall not exceed the total amount paid by you in the 3 months preceding the claim.',
      'StatuteProof is not liable for any indirect, incidental, consequential, or punitive damages, including loss of profit, regulatory penalty, or missed filing deadlines, arising from use of or inability to use the service.',
      'StatuteProof does not warrant that monitored sources are complete, current, or free from errors. Official source monitoring may be affected by website changes, publication delays, PDF extraction failures, access restrictions, or other factors outside our control.',
    ],
  },
  {
    heading: '8. Termination',
    paragraphs: [
      'You may cancel your plan at any time by contacting ' + CONTACT_EMAIL + '. Access continues until the end of the current billing period. Evidence records within your retention window remain downloadable for 14 days post-cancellation.',
      'StatuteProof may suspend or terminate access for breach of these Terms, non-payment, or where continued access poses a legal or compliance risk to the service.',
    ],
  },
  {
    heading: '9. Governing law and jurisdiction',
    paragraphs: [
      'These Terms are governed by the laws of England and Wales. Any disputes shall be subject to the exclusive jurisdiction of the courts of England and Wales, without prejudice to your rights under applicable mandatory consumer protection laws in your jurisdiction.',
    ],
  },
  {
    heading: '10. Contact',
    paragraphs: [
      'Questions about these Terms should be directed to ' + CONTACT_EMAIL + '. We aim to respond to all written enquiries within 5 business days.',
    ],
  },
]

const PRIVACY_SECTIONS = [
  {
    heading: '1. What data we collect',
    paragraphs: [
      'Account data: work email address, name (if provided), company or organisation name, job title (if provided), and the technical data created when your workspace is registered (workspace ID, created-at timestamp, plan identifier).',
      'Monitoring configuration: the list of regulatory sources assigned to your workspace, custom source URLs you submit, monitoring schedule settings, and source status records (run timestamps, change-status labels, failure reasons).',
      'Evidence records: for each monitored source run, we store the source URL, extracted content hash (SHA-256), UTC timestamp, change-status label, diff metadata, and file paths to stored snapshot artefacts. This data is the primary output of the service.',
      'Usage and session data: server-access logs (IP address, request timestamp, HTTP method and path, response code, user-agent string), session tokens, and feature interaction events where collected. We do not use third-party analytics trackers.',
      'Contact requests: if you submit the contact form, we store your name, email, company, and message text. This data is used solely to respond to your enquiry.',
    ],
  },
  {
    heading: '2. What data we do not collect',
    paragraphs: [
      'Do not submit passwords, private portal credentials, authentication tokens, or confidential internal documents as custom source URLs. StatuteProof is designed for public official sources and publicly accessible regulatory material only. We cannot be responsible for any confidential content submitted via custom source configuration.',
      'We do not collect payment card numbers or bank details directly. All payment processing is handled by Stripe, which is PCI-DSS Level 1 certified. We receive a Stripe customer reference and subscription status only.',
      'We do not collect, infer, or store regulatory compliance determinations about your organisation. The service generates monitoring intelligence — compliance decisions remain with your legal and compliance team.',
    ],
  },
  {
    heading: '3. How we use your data',
    paragraphs: [
      'To operate and deliver the service: running source monitoring jobs, generating evidence records, building alert drafts, delivering weekly briefs, and supporting workspace management.',
      'To communicate with you: sending monitoring alerts, evidence digest emails, billing receipts, service status notices, and responses to your support requests.',
      'To maintain and improve the service: diagnosing extraction failures, improving source adapters, monitoring system health, and developing new regulatory source coverage.',
      'We do not use your data for advertising, sell it to data brokers, or share it with third parties for their own marketing purposes.',
    ],
  },
  {
    heading: '4. Legal basis for processing (GDPR)',
    paragraphs: [
      'Contract performance: processing necessary to deliver the monitoring service you subscribed to, including source runs, evidence records, and account management.',
      'Legitimate interests: server logs and security monitoring to protect the integrity of the service and our other customers.',
      'Legal obligation: retaining billing and transaction records as required by applicable law.',
      'Consent: where you have specifically opted in to receive product updates or non-essential communications. You may withdraw this consent at any time.',
    ],
  },
  {
    heading: '5. Data retention',
    paragraphs: [
      'Evidence records and monitoring artefacts are retained for the period defined by your plan (30 days for Founding Pilot, 180 days for UAE Monitor). After the retention window expires, artefacts are permanently deleted from active storage.',
      'Account data is retained for the duration of your subscription and for up to 12 months after account closure to support any billing dispute or legal obligation.',
      'Server access logs are retained for up to 90 days.',
    ],
  },
  {
    heading: '6. Third-party processors',
    paragraphs: [
      'Stripe (stripe.com): payment processing. Stripe processes card data under its own Privacy Policy and PCI-DSS certification.',
      'Railway (railway.app) or equivalent cloud infrastructure: server hosting and database storage. Data is stored in the region selected at deployment (EU or US). We apply access controls and encryption at rest.',
      'OpenAI (openai.com): if AI-assisted brief generation is enabled, excerpts of extracted regulatory text may be sent to OpenAI\'s API for summarisation. We do not send account data or contact information. OpenAI\'s data use is governed by its API usage policies.',
      'Telegram (telegram.org): if you connect a Telegram account for regulatory alerts, your Telegram chat ID is stored to enable message delivery. We send only monitoring alerts to your Telegram account.',
    ],
  },
  {
    heading: '7. Your rights',
    paragraphs: [
      'Under applicable data protection law (including the UK GDPR and EU GDPR), you have the right to access a copy of the personal data we hold about you, request correction of inaccurate data, request deletion of your data (subject to legal retention requirements), object to or restrict certain processing, and data portability for data processed by consent or contract.',
      'To exercise any of these rights, contact ' + CONTACT_EMAIL + '. We will respond within 30 days. You also have the right to lodge a complaint with a supervisory authority in your country of residence.',
    ],
  },
  {
    heading: '8. Security',
    paragraphs: [
      'We apply industry-standard technical and organisational measures to protect your data, including TLS encryption in transit, encryption at rest for stored artefacts, access controls limited to authorised personnel, and WAL-mode SQLite database integrity.',
      'No system is completely secure. In the event of a personal data breach that is likely to result in a risk to your rights and freedoms, we will notify you and the relevant supervisory authority as required by applicable law.',
    ],
  },
  {
    heading: '9. Contact',
    paragraphs: [
      'Data protection questions and rights requests should be directed to ' + CONTACT_EMAIL + '. We aim to respond to all written data protection enquiries within 30 days.',
    ],
  },
]

const DISCLAIMER_SECTIONS = [
  {
    heading: 'Monitoring intelligence — not legal advice',
    paragraphs: [
      'StatuteProof reports are generated from monitored official-source records and are provided for information and compliance review support only. StatuteProof reports do not constitute legal advice, regulatory advice, compliance determination, or a legal opinion.',
      'StatuteProof does not replace qualified legal counsel, compliance professionals, MLROs, or other professional advisers.',
    ],
  },
  {
    heading: 'Source limitations',
    paragraphs: [
      'StatuteProof does not determine compliance outcomes, prevent fines, or confirm that all regulatory updates have been captured. Source monitoring may be affected by publication delays, website structure changes, PDF formatting, access restrictions, or content quality variations at the source.',
      'Users should verify official source material directly and review evidence records, hashes, timestamps, and diffs before relying on a report. Source readiness, extraction quality, and known limitations are disclosed before any pilot begins.',
    ],
  },
  {
    heading: 'AI-assisted content',
    paragraphs: [
      'Where brief generation or risk-scoring uses AI-assisted analysis, the output is a starting point for human review and should not be treated as a final compliance determination. AI-generated text may contain errors or inaccuracies and must be validated against primary source material.',
    ],
  },
]

const CONTENT = {
  terms:      { title: 'Terms of Service',        kicker: 'Terms',      sections: TERMS_SECTIONS      },
  privacy:    { title: 'Privacy Policy',           kicker: 'Privacy',    sections: PRIVACY_SECTIONS    },
  disclaimer: { title: 'Monitoring Disclaimer',    kicker: 'Disclaimer', sections: DISCLAIMER_SECTIONS },
}

// ─────────────────────────────────────────────────────────────────────────────

export default function LegalPage({ type = 'disclaimer', onBack }) {
  const page = CONTENT[type] || CONTENT.disclaimer

  return (
    <div className="min-h-dvh bg-[#07111F] text-slate-200">
      <header className="border-b border-slate-800 bg-[#06101D]/92 sticky top-0 z-10">
        <div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-6">
          <button
            onClick={onBack}
            className="flex items-center gap-2 text-sm text-slate-400 hover:text-white transition-colors"
          >
            <ArrowLeft className="h-4 w-4" />
            Back
          </button>
          <div className="flex items-center gap-2">
            <img src="/brand/regradar-logo-navbar.png" alt="StatuteProof" className="h-8 w-auto" />
            <span className="font-bold text-white">Statute<span className="text-[#16D9F5]">Proof</span></span>
          </div>
          <div className="w-14" />
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-16">
        <div className="sp-kicker mb-5 flex items-center gap-2">
          <ShieldCheck className="h-4 w-4" />
          {page.kicker}
        </div>
        <h1 className="text-4xl font-semibold text-white mb-2">{page.title}</h1>
        <p className="text-sm text-slate-500 mb-10">Last updated: June 2026</p>

        <div className="space-y-10">
          {page.sections.map((section) => (
            <section key={section.heading}>
              <h2 className="text-base font-semibold text-white mb-3">{section.heading}</h2>
              <div className="space-y-3">
                {section.paragraphs.map((para, i) => (
                  <p key={i} className="text-sm leading-relaxed text-slate-300">
                    {para}
                  </p>
                ))}
              </div>
            </section>
          ))}
        </div>

        <div className="mt-16 sp-panel p-5">
          <p className="text-xs text-slate-400 leading-relaxed">
            For questions about this document, contact{' '}
            <a
              href={`mailto:${CONTACT_EMAIL}`}
              className="text-[#16D9F5] hover:underline"
            >
              {CONTACT_EMAIL}
            </a>
            . StatuteProof is a monitoring intelligence service — not a regulated financial or legal services provider.
          </p>
        </div>
      </main>
    </div>
  )
}
